/**
 * openwop.codemod.manifest-version-deprecated — RFC 0178 §A.1 / migration row
 * C11.2: the registry version manifest's advisory `deprecated` boolean collides
 * with the JSON Schema 2020-12 `deprecated` annotation keyword once RFC 0178's
 * generator writes annotations onto schemas. The v2 manifest names the field
 * `versionDeprecated`. Pure rename on a manifest document; refuses when both
 * spellings are present with different values (it cannot pick); idempotent.
 * A re-signed manifest is C.10's job — this transform changes bytes, so the
 * detached signature MUST be regenerated by the registry, never copied.
 */
export const id = 'openwop.codemod.manifest-version-deprecated';
export const inputSchema = 'schemas/registry-version-manifest.schema.json';
export function transform(doc) {
  if (!doc || typeof doc !== 'object' || Array.isArray(doc)) throw new TypeError(`${id}: input must be a version manifest object`);
  if (!('deprecated' in doc)) return doc;
  if (typeof doc.deprecated !== 'boolean') throw new Error(`${id}: \`deprecated\` is not a boolean; refusing`);
  if ('versionDeprecated' in doc && doc.versionDeprecated !== doc.deprecated) throw new Error(`${id}: \`deprecated\` and \`versionDeprecated\` disagree; refusing to choose`);
  const { deprecated, ...rest } = doc;
  return { ...rest, versionDeprecated: deprecated };
}
