// AUTO-GENERATED by scripts/stamp-corpus-version.mjs at publish time.
// DO NOT EDIT — the committed values are a dev sentinel; the PUBLISHED package
// carries the real corpus tag (stamped via `prepublishOnly`). See the
// openwop-app extraction plan §"version-coherence gate": this is the anchor an
// extracted app uses to assert its vendored spec artifacts (schemas / fixtures /
// packs) match the corpus release this SDK was built from.

/** The nearest corpus `v*` release this SDK build corresponds to, e.g. "v1.1.7".
 *  `"0.0.0-dev"` in a working tree / unstamped build. */
export const CORPUS_VERSION = '0.0.0-dev' as const;

/** The exact monorepo commit this SDK build was produced from (short SHA). */
export const CORPUS_COMMIT = 'unknown' as const;
