#!/usr/bin/env python3
"""v2 charter Phase 3, P3-C — derive api/v2/openapi.yaml, api/v2/asyncapi.yaml,
api/seams-v2.yaml and spec/v2/path-manifest.json from the v1 API documents and
the children's decisions (RFC 0171 §C/§E, RFC 0172 §A/§C, RFC 0168 §C, RFC 0173 §C).

Python + PyYAML because the corpus has no Node YAML parser and the v1 documents
are YAML; the outputs are committed and `--check` compares a regeneration to
the committed bytes, so a CI without PyYAML fails loudly, never silently.

What the derivation does (every rule cites its RFC):
  - path keys lose their /v1 prefix (RFC 0172 §A.2: bare origin, unversioned
    v2 keys); /v1/openapi.json → /openapi.json;
  - the nine seam/test-mode operations (/v1/host/sample/*,
    /v1/host/workspace/files*, /v1/packs-test/*) leave the canonical document
    for api/seams-v2.yaml under /conformance/seams/… (RFC 0168 §C.1–§C.2);
  - every operation takes the OpenWOP-Version request header and every
    response declares it (RFC 0172 §A.3–§A.4);
  - X-Dedup → OpenWOP-Dedup, X-Force-Engine-Version → OpenWOP-Force-Engine-Version,
    X-Pack-Sha256 → OpenWOP-Pack-Sha256, X-Pack-Signing-Method →
    OpenWOP-Pack-Signing-Method; Capabilities-Etag → ETag (RFC 0171 §C.1);
  - the poll cursor is afterSequence, omission = from the first event; the
    response is {runId, events, lastSequence, status, isTerminal} (RFC 0171 §E.2);
  - $refs point into schemas/v2/ (../../schemas/v2/…); the two one-member enum
    components become $refs to the generated error envelope (RFC 0171 §B.1);
  - the interrupt token path parameter gains the ow2.<alg>.<kid>.<payload>.<mac>
    grammar, accepting the v1 two-segment form through the overlap (RFC 0170 §E.1);
  - three RFC 0173 read surfaces are added on unversioned keys:
    GET /host/effect-seams, GET /runs/{runId}/compensation, GET /runs/{runId}/effects;
    GET /host/events is the documented default hostEvents address (RFC 0171 §E.1);
  - AsyncAPI: server pathname '' and one runEvents channel whose address IS the
    OpenAPI key, with streamMode as a pattern over the closed set and its
    comma-separated combinations; hostEvents at /host/events (RFC 0171 §E.1);
  - info.version reads spec/v2/release.json (RFC 0172 §B axis 14).

  --write   regenerate the four outputs        --check  compare to the committed files
"""
import json, re, sys, copy, io
from pathlib import Path
try:
    import yaml
except ModuleNotFoundError:
    sys.exit('derive-v2-api: PyYAML is required (python3 -m pip install pyyaml) — the check refuses to pass without it')

ROOT = Path(__file__).resolve().parent.parent
V1 = yaml.safe_load((ROOT / 'api' / 'openapi.yaml').read_text())
A1 = yaml.safe_load((ROOT / 'api' / 'asyncapi.yaml').read_text())
REL = json.loads((ROOT / 'spec' / 'v2' / 'release.json').read_text())
SEAM = re.compile(r'^/v1/(host/sample/|host/workspace/files|packs-test/)')
HEADER_RENAME = {'openwop-Idempotent-Replay': 'OpenWOP-Idempotent-Replay', 'X-Idempotent-Replay': 'OpenWOP-Idempotent-Replay', 'X-Dedup': 'OpenWOP-Dedup', 'X-Force-Engine-Version': 'OpenWOP-Force-Engine-Version', 'X-Pack-Sha256': 'OpenWOP-Pack-Sha256', 'X-Pack-Signing-Method': 'OpenWOP-Pack-Signing-Method', 'Capabilities-Etag': 'ETag'}
V2_SCHEMAS = {p.relative_to(ROOT / 'schemas' / 'v2').as_posix() for p in (ROOT / 'schemas' / 'v2').rglob('*.schema.json')}

def rewrite(node, depth_prefix='../../schemas/v2/'):
    if isinstance(node, dict):
        out = {}
        for k, v in node.items():
            if k == '$ref' and isinstance(v, str) and '../schemas/' in v and 'schemas/v2/' not in v:
                rel = v.split('../schemas/')[1]
                file = rel.split('#')[0]
                if file not in V2_SCHEMAS:
                    raise SystemExit(f'derive-v2-api: {v} names a schema the v2 tree does not carry ({file})')
                out[k] = depth_prefix + rel
            elif k in HEADER_RENAME and isinstance(v, dict):
                out[HEADER_RENAME[k]] = rewrite(v, depth_prefix)
            else:
                out[k] = rewrite(v, depth_prefix)
        if isinstance(out.get('name'), str) and out.get('name') in HEADER_RENAME and out.get('in') == 'header':
            out['name'] = HEADER_RENAME[out['name']]
        return out
    if isinstance(node, list):
        return [rewrite(x, depth_prefix) for x in node]
    return node

def v2_openapi_and_seams():
    doc = copy.deepcopy(V1)
    doc['info']['version'] = REL['version']
    doc['info']['title'] = 'OpenWOP v2 API'
    doc['info']['description'] = ('GENERATED by scripts/derive-v2-api.py from api/openapi.yaml and the RFC 0167 children (v2 charter Phase 3, P3-C). '
        'Bare origin, unversioned path keys, negotiation by `OpenWOP-Version` + `protocolVersions[]` (RFC 0172 §A). '
        'No seam or test-mode operation lives here (RFC 0168 §C.2 — see api/seams-v2.yaml). Every non-standard header is `OpenWOP-<Name>` (RFC 0171 §C.1). '
        'Retry timing lives in `Retry-After` only (RFC 0171 §B.2).')
    seams = {'openapi': doc['openapi'], 'info': {'title': 'OpenWOP conformance seams profile (openwop-conformance-seams-v2)', 'version': REL['version'],
             'description': 'GENERATED by scripts/derive-v2-api.py. RFC 0168 §C: the seams are a versioned conformance profile with their own document and path space (/conformance/seams/…), validated against the canonical v2 schemas with no tolerance path, forbidden from the capability namespace (a host advertises the profile, never a testSeams flag). This document carries the nine operations the v1 canonical document used to carry; the remaining host-sample-test-seams.md paths enter with the 2.0.0 suite driver (P3-E).'},
             'servers': copy.deepcopy(doc.get('servers', [])), 'paths': {}, 'components': copy.deepcopy(doc.get('components', {}))}
    paths = {}
    for key, item in doc['paths'].items():
        if SEAM.match(key):
            nk = re.sub(r'^/v1/host/sample/', '/conformance/seams/sample/', key)
            nk = re.sub(r'^/v1/host/workspace/files', '/conformance/seams/workspace/files', nk)
            nk = re.sub(r'^/v1/packs-test/', '/conformance/seams/packs-test/', nk)
            seams['paths'][nk] = item
            continue
        nk = key
        if key.startswith('/v1/'):
            nk = key[3:]
        paths[nk] = item
    # RFC 0173 read surfaces + hostEvents default address
    paths['/host/effect-seams'] = {'get': {'tags': ['Host'], 'operationId': 'getEffectSeamManifest', 'summary': 'The host-declared effect-seam manifest (RFC 0173 §C)', 'description': 'Every outbound effect seam replay suppression covers. A seam omitted here is invisible to the suite; the RFC 0140 R5 audit is the control.', 'responses': {'200': {'description': 'The manifest.', 'content': {'application/json': {'schema': {'$ref': '../../schemas/v2/effect-seam-manifest.schema.json'}}}}, '401': {'$ref': '#/components/responses/Unauthenticated'}}}}
    paths['/runs/{runId}/compensation'] = {'parameters': [{'$ref': '#/components/parameters/RunId'}], 'get': {'tags': ['Runs'], 'operationId': 'getRunCompensation', 'summary': 'Compensation plan and attempts for a run (RFC 0173 §C.1)', 'description': 'The read projection that makes compensation a core obligation with a deployed-wire witness (RFC 0151 G9 / RFC 0173 §B).', 'responses': {'200': {'description': 'The projection.', 'content': {'application/json': {'schema': {'$ref': '../../schemas/v2/compensation-projection.schema.json'}}}}, '404': {'$ref': '#/components/responses/NotFound'}}}}
    paths['/runs/{runId}/effects'] = {'parameters': [{'$ref': '#/components/parameters/RunId'}], 'get': {'tags': ['Runs'], 'operationId': 'getRunEffects', 'summary': 'The Layer-2 effect ledger for a run (RFC 0173 §C.2)', 'description': 'Business-identity keyed effect records; the witness for the Layer-2 effect-identity obligation.', 'responses': {'200': {'description': 'The ledger projection.', 'content': {'application/json': {'schema': {'$ref': '../../schemas/v2/effect-ledger-projection.schema.json'}}}}, '404': {'$ref': '#/components/responses/NotFound'}}}}
    paths['/host/events'] = {'get': {'tags': ['Host'], 'operationId': 'streamHostEvents', 'summary': 'Host-scoped events (heartbeat.*) as SSE (RFC 0171 §E.1)', 'description': 'The documented default hostEvents address; a host MAY declare another under `heartbeat.deliveryChannel`. Content-free of run data.', 'responses': {'200': {'description': 'text/event-stream of hostEvents messages.', 'content': {'text/event-stream': {'schema': {'type': 'string'}}}}, '401': {'$ref': '#/components/responses/Unauthenticated'}}}}
    doc['paths'] = paths
    comps = doc.setdefault('components', {})
    comps.setdefault('parameters', {})['OpenWOPVersion'] = {'name': 'OpenWOP-Version', 'in': 'header', 'required': False, 'schema': {'type': 'string', 'pattern': '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$'}, 'description': 'RFC 0172 §A.3 — selects a listed major.minor; absent ⇒ the host\'s `preferredVersion`; unlisted ⇒ 406 protocol_version_unsupported.'}
    comps.setdefault('headers', {})['OpenWOPVersion'] = {'schema': {'type': 'string'}, 'description': 'RFC 0172 §A.4 — the contract that produced this response; MUST equal the one used.', 'required': True}
    # poll cursor + interrupt token grammar + per-operation header + one-member enums
    for key, item in doc['paths'].items():
        for method, op in list(item.items()):
            if method not in ('get', 'post', 'put', 'delete', 'patch'):
                continue
            params = op.setdefault('parameters', [])
            if not any(isinstance(p, dict) and p.get('$ref') == '#/components/parameters/OpenWOPVersion' for p in params):
                params.append({'$ref': '#/components/parameters/OpenWOPVersion'})
            for p in params:
                if isinstance(p, dict) and p.get('name') == 'lastSequence':
                    p.update({'name': 'afterSequence', 'schema': {'type': 'integer', 'minimum': 0}, 'description': 'RFC 0171 §E.2 — return events with `sequence > afterSequence`; omission means from the first event (sequence 0). `lastSequence` and `since` are gone.'})
                if isinstance(p, dict) and p.get('name') == 'token' and p.get('in') == 'path':
                    p['schema'] = {'type': 'string', 'pattern': '^(ow2\\.hs256\\.[A-Za-z0-9._~-]{1,128}\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+|[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+)$'}
                    p['description'] = 'RFC 0170 §E.1 — `ow2.<alg>.<kid>.<payload>.<mac>`; the v1 two-segment form is accepted under kid legacy until its expiresAt (RFC 0176 §B.2).'
            for p in params:
                if isinstance(p, dict) and p.get('name') == 'streamMode' and p.get('in') == 'query':
                    p['schema'] = {'type': 'string', 'pattern': '^(values|(updates|messages|debug)(,(updates|messages|debug))*)$', 'default': 'updates'}
                    p['description'] = 'RFC 0171 §E.1 — the closed set and its comma-separated combinations; `values` never combines.'
            op['parameters'] = [p for p in params if not (isinstance(p, dict) and p.get('name') == 'since')]
            for code, resp in op.get('responses', {}).items():
                if isinstance(resp, dict) and '$ref' not in resp:
                    resp.setdefault('headers', {})['OpenWOP-Version'] = {'$ref': '#/components/headers/OpenWOPVersion'}
            if op.get('operationId') == 'pollRunEvents':
                ok = op['responses'].get('200', {})
                ok['content'] = {'application/json': {'schema': {'type': 'object', 'additionalProperties': False, 'required': ['runId', 'events', 'lastSequence', 'status', 'isTerminal'], 'properties': {'runId': {'$ref': '../../schemas/v2/ids.schema.json#/$defs/runId'}, 'events': {'type': 'array', 'items': {'$ref': '../../schemas/v2/run-event.schema.json'}}, 'lastSequence': {'type': 'integer', 'minimum': -1, 'description': 'The highest sequence in the log at the time of the response (one meaning); -1 when the log is empty.'}, 'status': {'type': 'string'}, 'isTerminal': {'type': 'boolean'}}}}}
    for name in ('RunClaimConflict', 'UnsupportedStreamMode'):
        if name in comps.get('schemas', {}):
            comps['schemas'][name] = {'$ref': '../../schemas/v2/error-envelope.schema.json', 'description': f'RFC 0171 §B.1 — the former one-member enum `{name}` is the generated error envelope (`error` carries the code).'}
    for resp in comps.get('responses', {}).values():
        if isinstance(resp, dict) and 'headers' in resp:
            resp['headers'].pop('Capabilities-Etag', None)
    doc = rewrite(doc)
    seams['security'] = copy.deepcopy(doc.get('security', []))
    seams = rewrite(seams, '../schemas/v2/')  # api/seams-v2.yaml lives one level up from api/v2/
    return doc, seams

def v2_asyncapi():
    comps = rewrite(copy.deepcopy(A1.get('components', {})))
    comps.setdefault('messages', {})['RunEvent'] = {'name': 'runEvent', 'title': 'Run event (RFC 0171 §A)', 'contentType': 'text/event-stream', 'payload': {'$ref': '../../schemas/v2/run-event.schema.json'}, 'description': 'One SSE frame per run event; `event:` is the v2 type, `id:` is the sequence (RFC 0171 §A.3).'}
    return {
        'asyncapi': A1['asyncapi'],
        'info': {'title': 'OpenWOP v2 event streams', 'version': REL['version'], 'description': 'GENERATED by scripts/derive-v2-api.py (RFC 0171 §E.1, RFC 0172 §C.2). One run-events channel whose address is the OpenAPI path key; the server pathname is empty (bare origin). streamMode is a pattern over the closed set and its comma-separated combinations (`values` never combines). hostEvents has a real address (RFC 0171 §E.1) — the documented default; a host MAY declare another under `heartbeat.deliveryChannel`.'},
        'defaultContentType': 'text/event-stream',
        'servers': {'production': {'host': '{host}', 'pathname': '', 'protocol': 'https', 'variables': {'host': {'default': 'api.example.com'}}}},
        'channels': {
            'runEvents': {'address': '/runs/{runId}/events', 'title': 'Run event stream (SSE)', 'parameters': {'runId': {'description': 'ids.schema.json#/$defs/runId'}},
                          'messages': {'runEvent': {'$ref': '#/components/messages/RunEvent'}}},
            'hostEvents': {'address': '/host/events', 'title': 'Host-scoped events (heartbeat.*)', 'messages': {'heartbeatEvaluated': {'$ref': '#/components/messages/HeartbeatEvaluated'}, 'heartbeatStateChanged': {'$ref': '#/components/messages/HeartbeatStateChanged'}}},
        },
        'operations': {
            'subscribeRunEvents': {'action': 'receive', 'channel': {'$ref': '#/channels/runEvents'}, 'title': 'Subscribe to a run\'s events',
                                   'description': 'Long-lived SSE subscription; auto-closes on a terminal run event; `Last-Event-ID` resumes from the sequence AFTER the supplied one. Mixed mode is union-of-filters with per-event `event:` labels (stream-modes).',
                                   'bindings': {'http': {'method': 'GET', 'query': {'type': 'object', 'additionalProperties': False, 'properties': {'streamMode': {'type': 'string', 'pattern': '^(values|(updates|messages|debug)(,(updates|messages|debug))*)$', 'default': 'updates'}}}}}},
            'subscribeHostEvents': {'action': 'receive', 'channel': {'$ref': '#/channels/hostEvents'}, 'title': 'Subscribe to host events', 'bindings': {'http': {'method': 'GET'}}},
        },
        'components': comps,
    }

def manifest(doc, adoc):
    ops = []
    for key, item in doc['paths'].items():
        for method, op in item.items():
            if method in ('get', 'post', 'put', 'delete', 'patch'):
                ops.append({'method': method.upper(), 'path': key, 'operationId': op.get('operationId')})
    ops.sort(key=lambda o: (o['path'], o['method']))
    chans = [{'name': n, 'address': c['address']} for n, c in adoc['channels'].items()]
    return {'$comment': 'GENERATED by scripts/derive-v2-api.py (RFC 0172 §C.2 / RFC 0168 §C.2): the canonical v2 operations and channels; no seam or test-mode operation; every path unversioned. check-path-parity.mjs compares this to both API documents.', 'generatedFrom': ['api/v2/openapi.yaml', 'api/v2/asyncapi.yaml'], 'serverUrl': 'https://{host}', 'operations': ops, 'channels': chans, 'counts': {'operations': len(ops), 'channels': len(chans)}}

def prune_unused(doc):
    """Drop components no operation in THIS document references (a seam-only
    parameter has no business in the canonical document and vice versa)."""
    text = json.dumps({k: v for k, v in doc.items() if k != 'components'})
    comps = doc.get('components', {})
    for group in ('parameters', 'responses', 'schemas', 'headers', 'requestBodies'):
        if group not in comps:
            continue
        changed = True
        while changed:
            changed = False
            alltext = text + json.dumps({g: v for g, v in comps.items()})
            for name in list(comps[group]):
                if f'#/components/{group}/{name}"' not in alltext.replace(f'"{group}": {{"{name}"', ''):
                    # referenced nowhere except by its own definition
                    refs = alltext.count(f'#/components/{group}/{name}"')
                    if refs == 0:
                        del comps[group][name]; changed = True
        if not comps[group]:
            del comps[group]
    return doc

def headers_doc(doc):
    """spec/v2/core/headers.md — GENERATED (RFC 0171 §C.1): every non-standard
    header is declared in OpenAPI, so the table that enumerates headers enumerates
    all of them."""
    req, resp = {}, {}
    comps = doc.get('components', {})
    def param_of(p):
        if '$ref' in p:
            return comps.get('parameters', {}).get(p['$ref'].split('/')[-1], {})
        return p
    for key, item in doc['paths'].items():
        for method, op in item.items():
            if method not in ('get', 'post', 'put', 'delete', 'patch'):
                continue
            for p in op.get('parameters', []) + item.get('parameters', []):
                pp = param_of(p)
                if pp.get('in') == 'header':
                    req.setdefault(pp['name'], {'desc': pp.get('description', '').split('\n')[0], 'ops': set()})['ops'].add(op.get('operationId'))
            for code, r in op.get('responses', {}).items():
                rr = comps.get('responses', {}).get(r['$ref'].split('/')[-1], {}) if '$ref' in r else r
                for hn, h in (rr.get('headers') or {}).items():
                    hh = comps.get('headers', {}).get(h['$ref'].split('/')[-1], {}) if '$ref' in h else h
                    resp.setdefault(hn, {'desc': (hh.get('description') or '').split('\n')[0], 'ops': set()})['ops'].add(op.get('operationId'))
    lines = ['# Headers', '', '> **Status: Draft · v2.0.0-rc (2026-09-03) · RFC 0171 §C.1, RFC 0172 §A.3–§A.4.** GENERATED by `scripts/derive-v2-api.py` from `api/v2/openapi.yaml`; do not edit.', '',
             '## Why this exists', '', 'RFC 0171 §C.1: every non-standard header is `OpenWOP-<Name>` and every header is declared in OpenAPI, so this table — generated from the same declaration — enumerates all of them. A header that is not in this table is not part of the protocol. Standard headers keep their standard names (`Idempotency-Key`, `ETag`, `If-None-Match`, `Last-Event-ID`, `Retry-After`, `Authorization`).', '',
             '## Request headers', '', '| Header | Operations | Meaning |', '| --- | --- | --- |']
    for n in sorted(req):
        lines.append(f"| `{n}` | {len(req[n]['ops'])} | {req[n]['desc']} |")
    lines += ['', '## Response headers', '', '| Header | Operations | Meaning |', '| --- | --- | --- |']
    for n in sorted(resp):
        lines.append(f"| `{n}` | {len(resp[n]['ops'])} | {resp[n]['desc']} |")
    lines += ['', '## Webhook delivery headers', '', 'Declared in `webhooks.md`, not in OpenAPI (the host is the client): `OpenWOP-Webhook-Id`, `OpenWOP-Event-Type`, `OpenWOP-Timestamp`, `OpenWOP-Signature`, `OpenWOP-Signature-Algorithm` (RFC 0165 §C.1). The `X-openwop-*` family is emitted beside them through the overlap and removed at v1 end-of-support (`spec/v1/deprecations.json` `webhook-x-header-family`).', '',
              '## Removed in v2', '', '`Capabilities-Etag` (the standard `ETag`/`If-None-Match` pair applies to the discovery document), `X-Dedup`, `X-Force-Engine-Version`, `X-Pack-Sha256`, `X-Pack-Signing-Method` (renamed under the one scheme), `X-openwop-*` (webhooks), `openwop-Webhook-Signature` (SDK-only). Each has a `spec/v1/deprecations.json` row with a removal trigger.', '']
    return '\n'.join(lines)

def dump(obj):
    text = yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, width=120)
    # prose mentions of renamed headers inside descriptions (RFC 0171 §C.1)
    for old_name, new_name in (('openwop-Idempotent-Replay', 'OpenWOP-Idempotent-Replay'), ('X-Idempotent-Replay', 'OpenWOP-Idempotent-Replay')):
        text = text.replace(old_name, new_name)
    return text

doc, seams = v2_openapi_and_seams(); doc = prune_unused(doc); seams = prune_unused(seams); adoc = v2_asyncapi(); man = manifest(doc, adoc)
outputs = {ROOT / 'spec' / 'v2' / 'core' / 'headers.md': headers_doc(doc), ROOT / 'api' / 'v2' / 'openapi.yaml': dump(doc), ROOT / 'api' / 'v2' / 'asyncapi.yaml': dump(adoc), ROOT / 'api' / 'seams-v2.yaml': dump(seams), ROOT / 'spec' / 'v2' / 'path-manifest.json': json.dumps(man, indent=2, ensure_ascii=False) + '\n'}
if '--write' in sys.argv:
    for p, s in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(s); print(f'wrote {p.relative_to(ROOT)}')
    print(f"derive-v2-api: {man['counts']['operations']} operations, {man['counts']['channels']} channels, {len(seams['paths'])} seam paths")
else:
    stale = [str(p.relative_to(ROOT)) for p, s in outputs.items() if not p.exists() or p.read_text() != s]
    if stale:
        print('derive-v2-api: stale — ' + ', '.join(stale) + '. Run: python3 scripts/derive-v2-api.py --write', file=sys.stderr); sys.exit(1)
    print(f"=== derive-v2-api OK — {man['counts']['operations']} operations / {man['counts']['channels']} channels in parity with the committed outputs ===")
